#ifndef T100PSVMCOMMON_H
#define T100PSVMCOMMON_H

#include <wx/wx.h>

enum {
    T100PSVM_MENU_ITEM_FILE_NEW             = wxID_HIGHEST + 1,
    T100PSVM_MENU_ITEM_FILE_OPEN,
    T100PSVM_MENU_ITEM_FILE_CLOSE,
    T100PSVM_MENU_ITEM_FILE_SAVE,
    T100PSVM_MENU_ITEM_FILE_SAVE_AS,
    T100PSVM_MENU_ITEM_FILE_QUIT,
    T100PSVM_MENU_ITEM_VM_START,
    T100PSVM_MENU_ITEM_VM_STOP,
    T100PSVM_MENU_ITEM_VM_REBOOT,
    T100PSVM_MENU_ITEM_DEBUG_START,
    T100PSVM_MENU_ITEM_DEBUG_STOP,
    T100PSVM_MENU_ITEM_HELP_ABOUT
};

#endif // T100PSVMCOMMON_H
