#ifndef T100VHDCOMMON_H
#define T100VHDCOMMON_H


typedef enum{
    T100VHD_STORAGE_TYPE_NONE,
    T100VHD_STORAGE_TYPE_FIXED,
    T100VHD_STORAGE_TYPE_DYNAMIC
}T100VHD_STORAGE_TYPE;

#endif // T100VHDCOMMON_H
