#ifndef T100CONSOLECOMMON_H
#define T100CONSOLECOMMON_H


#include "T100Common.h"

#define     T100CONSOLE_PROMPT_DEFAULT          "?"
#define     T100CONSOLE_SEPARATOR_DEFAULT       " "

#define     T100COMMAND_VECTOR          T100STDSTRING_VECTOR


#endif // T100CONSOLECOMMON_H
