{
	"all": {
		"flow": [
			{
				"name": "get",
				"value": "/login.html"
			},
			{
				"name"	: "form",
				"value"	: "submit",
				"data"	: {
					"username": "admin",
					"password": "111111"
				}
			},
			{
				"name": "verify",
				"verify": {
					"type": "alert",
					"success": "",
					"failure": ""
				}
			}
		],
		"dataset": [
			{
				"username": "skynet",
				"password": "111111"
			}
		]
	}
}