#ifndef T100ELEMENTCOMMON_H
#define T100ELEMENTCOMMON_H


namespace T100Painter{

typedef enum{
    T100ELEMENT_NONE            = 0,
    //
    T100ELEMENT_GRAPHICS_CIRCLE,
    T100ELEMENT_GRAPHICS_RECTANGLE,
    //
    T100ELEMENT_DIAGRAM_MODULE,
    //
    T100ELEMENT_MAX
}T100ELEMENT_TYPE;

}


#endif // T100ELEMENTCOMMON_H
