#ifndef T100WPAINTERCOMMON_H
#define T100WPAINTERCOMMON_H

typedef enum{
    T100CANVAS_STATE_NONE           = 0,
    //
    T100CANVAS_STATE_PAINT,
    T100CANVAS_STATE_SELECTED,
    T100CANVAS_STATE_SIZING,
    T100CANVAS_STATE_EDIT,
    //
    T100CANVAS_STATE_MAX
}T100CANVAS_STATE;

#endif // T100WPAINTERCOMMON_H
