#ifndef T100PROJECTCOMMON_H
#define T100PROJECTCOMMON_H

#include <wx/wx.h>

enum {
    T100PROJECT_MENU_WORKSPACE_NEW      = wxID_HIGHEST + 1,
    T100PROJECT_MENU_WORKSPACE_OPEN,
    T100PROJECT_MENU_WORKSPACE_CLOSE,
    T100PROJECT_MENU_WORKSPACE_SAVE,
    T100PROJECT_MENU_WORKSPACE_SAVE_AS,
    T100PROJECT_MENU_WORKSPACE_QUIT,
    T100PROJECT_MENU_PROJECT_NEW,
    T100PROJECT_MENU_PROJECT_OPEN,
    T100PROJECT_MENU_PROJECT_CLOSE,
    T100PROJECT_MENU_PROJECT_SAVE,
    T100PROJECT_MENU_PROJECT_SAVE_AS,
    T100PROJECT_MENU_FILE_NEW,
    T100PROJECT_MENU_FILE_OPEN,
    T100PROJECT_MENU_FILE_CLOSE,
    T100PROJECT_MENU_FILE_SAVE,
    T100PROJECT_MENU_FILE_SAVE_AS,
    T100PROJECT_MENU_EDIT_UNDO,
    T100PROJECT_MENU_EDIT_REDO,
    T100PROJECT_MENU_EDIT_CUT,
    T100PROJECT_MENU_EDIT_COPY,
    T100PROJECT_MENU_EDIT_PASTE,
    T100PROJECT_MENU_VIEW_WORKSPACE,
    T100PROJECT_MENU_VIEW_SEARCH,
    T100PROJECT_MENU_VIEW_OUTPUT,
    T100PROJECT_MENU_SEARCH_FIND,
    T100PROJECT_MENU_SEARCH_REPLACE,
    T100PROJECT_MENU_COMPILE_RUN,
    T100PROJECT_MENU_COMPILE_BUILD_AND_RUN,
    T100PROJECT_MENU_COMPILE_BUILD,
    T100PROJECT_MENU_COMPILE_CLEAN,
    T100PROJECT_MENU_COMPILE_REBUILD,
    T100PROJECT_MENU_SETUP_EDITOR,
    T100PROJECT_MENU_SETUP_COMPILER,
    T100PROJECT_MENU_HELP_ABOUT
};

enum {
    T100PROJECT_TREE_ITEM_NONE,
    T100PROJECT_TREE_ITEM_WORKSPACE,
    T100PROJECT_TREE_ITEM_PROJECT,
    T100PROJECT_TREE_ITEM_FOLDER,
    T100PROJECT_TREE_ITEM_FILE
};

enum {
    T100PROJECT_TREE_MENU_WORKSPACE_PROPERTIES,
    T100PROJECT_TREE_MENU_PROJECT_NEW,
    T100PROJECT_TREE_MENU_FILE_NEW,
    T100PROJECT_TREE_MENU_FOLDER_NEW,
    T100PROJECT_TREE_MENU_CLASS_NEW,
    T100PROJECT_TREE_MENU_MODULE_NEW
};

enum {
    T100PROJECT_EDITOR_MENU_CLEAR
};

#endif // T100PROJECTCOMMON_H
