#ifndef T1003DEDITORUICOMMON_H
#define T1003DEDITORUICOMMON_H

typedef enum{
    T100SCENE_ITEM_CATEGORY_ROOT,
    T100SCENE_ITEM_CATEGORY_ENTITY,
    T100SCENE_ITEM_CATEGORY_MESH,
    T100SCENE_ITEM_CATEGORY_LIGHT,
    T100SCENE_ITEM_CATEGORY_CAMERA,
    T100SCENE_ITEM_CATEGORY_MATERIAL,
    T100SCENE_ITEM_CATEGORY_TEXTURE,
    T100SCENE_ITEM_CATEGORY_AUDIO,
    T100SCENE_ITEM_CATEGORY_VIDEO,
    T100SCENE_ITEM_CATEGORY_SAMPLER,

    T100SCENE_ITEM_ENTITY,
    T100SCENE_ITEM_MESH,
    T100SCENE_ITEM_LIGHT,
    T100SCENE_ITEM_CAMERA,
    T100SCENE_ITEM_MATERIAL,
    T100SCENE_ITEM_TEXTURE,
    T100SCENE_ITEM_AUDIO,
    T100SCENE_ITEM_VIDEO,
    T100SCENE_ITEM_SAMPLER
}T1003DEDITOR_SCENE_ITEM_TYPE;

#endif // T1003DEDITORUICOMMON_H
